version: '3'
services:
  reverse-proxy:
    extra_hosts:
     - "host.docker.internal:host-gateway"
    image: nginx:latest
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/sites-enabled:/etc/nginx/sites-enabled
     - ./nginx/ssl:/etc/nginx/ssl
    ports:
     - "80:80"
     - "443:443"